'use strict'

exports.ERR_NOT_VALID_URL = 'ERR_NOT_VALID_URL'
exports.ERR_MISSING_URL = 'ERR_MISSING_URL'
exports.ERR_NOT_SUITABLE_URL = 'ERR_NOT_SUITABLE_URL'
exports.ERR_NOT_STREAMABLE = 'ERR_NOT_STREAMABLE'
